# This is an example docker compose file for running a full Postal installation.
# Due to its nature, it doesn't attempt too much security (for example, communication
# between services is not secured at all).
version: "3.9"

services:
  # MariaDB used for persisting all data
  mariadb:
    profiles: ["db", "postal", "tools"]
    image: mariadb
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MARIADB_DATABASE: postal
      MARIADB_USER: postal
      MARIADB_PASSWORD: postal
      MARIADB_ROOT_PASSWORD: postal

  # Runs the Postal web server
  postal_web:
    profiles: ["postal"]
    image: postalhq/postal:latest
    command: bundle exec puma -C config/puma.rb
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config
    ports:
      - 5000:5000
    depends_on:
      - mariadb

  # Bootstraps all application configuration by generating an example config file
  # as well as generating new keys and self-signed certificates for other
  # components. These can be kept or replaced as necessary.
  bootstrap_config:
    profiles: ["tools"]
    image: postalhq/postal:latest
    command: bundle exec ruby script/generate_initial_config.rb
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config
    depends_on:
      - mariadb

  # Initialize the database by loading the schema and adding any seed data that is
  # needed to run the application for the first run.
  init:
    profiles: ["tools"]
    image: postalhq/postal:latest
    command: bundle exec rake db:schema:load db:seed
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config
    depends_on:
      - mariadb

  # Creates a new super admin user by prompting for the details in the terminal and then
  # creating the user as appropriate in the database.
  make_user:
    profiles: ["tools"]
    image: postalhq/postal:latest
    command: bundle exec ruby script/make_user.rb
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config
    depends_on:
      - mariadb
