version: "3.9"
services:
  web:
    image: postalhq/postal:latest
    command: bundle exec puma -C config/puma.rb
    network_mode: host
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config

  smtp:
    image: postalhq/postal:latest
    command: bundle exec rake postal:smtp_server
    network_mode: host
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config

  worker:
    image: postalhq/postal:latest
    command: bundle exec ruby script/worker.rb
    network_mode: host
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config

  cron:
    image: postalhq/postal:latest
    command: bundle exec rake postal:cron
    network_mode: host
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config

  requeuer:
    image: postalhq/postal:latest
    command: bundle exec rake postal:requeuer
    network_mode: host
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config

  # Initialize the database by loading the schema and adding any seed data that is
  # needed to run the application for the first run.
  init_db:
    profiles: ["tools"]
    image: postalhq/postal:latest
    command: bundle exec rake db:schema:load db:seed
    network_mode: host
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config

  # Creates a new super admin user by prompting for the details in the terminal and then
  # creating the user as appropriate in the database.
  make_user:
    profiles: ["tools"]
    image: postalhq/postal:latest
    command: bundle exec ruby script/make_user.rb
    network_mode: host
    environment:
      POSTAL_CONFIG_ROOT: /config
    volumes:
      - ./config:/config
